# Generated by Django 5.1.4 on 2025-01-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default="delete.user@gmail.com",
                max_length=255,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
