# Generated by Django 5.1.4 on 2025-01-31 11:38

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_label_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizLabels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="category",
            name="unique category name",
        ),
        migrations.RemoveConstraint(
            model_name="label",
            name="unique label name",
        ),
        migrations.RemoveConstraint(
            model_name="quiz",
            name="unique quiz title",
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="unique_category_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="label",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"), name="unique_label_name"
            ),
        ),
        migrations.AddField(
            model_name="quizlabels",
            name="label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.label"
            ),
        ),
        migrations.AddField(
            model_name="quizlabels",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.quiz"
            ),
        ),
        migrations.RemoveField(model_name="quiz", name="labels"),
        migrations.AddField(
            model_name="quiz",
            name="labels",
            field=models.ManyToManyField(
                related_name="quiz", through="api.QuizLabels", to="api.label"
            ),
        ),
        migrations.AddConstraint(
            model_name="quiz",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("title"), name="unique_quiz_title"
            ),
        ),
    ]
