# Generated by Django 5.1.4 on 2025-03-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_question_correct_answer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
