# Generated by Django 5.1.4 on 2025-03-25 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_remove_quiz_category_delete_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="correct_answer",
        ),
        migrations.AddField(
            model_name="answer",
            name="correct_answer_for",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="correct_answer_to_question",
                to="api.question",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="timestamp",
            field=models.CharField(default="00:00"),
        ),
        migrations.AddField(
            model_name="quiz",
            name="type",
            field=models.CharField(
                choices=[("YT", "Youtube"), ("UP", "Upload")],
                default="upload",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="answer",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="question",
            name="question",
            field=models.CharField(),
        ),
    ]
