# Generated by Django 5.1.4 on 2025-03-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_remove_question_correct_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="type",
            field=models.CharField(
                choices=[("YT", "Youtube"), ("UP", "Upload")], max_length=7
            ),
        ),
    ]
