# Generated by Django 5.1.4 on 2025-04-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_quiz_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="embed_url",
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
