# Generated by Django 5.1.4 on 2025-04-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_quiz_embed_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="labels",
        ),
        migrations.RemoveField(
            model_name="quizlabels",
            name="label",
        ),
        migrations.RemoveField(
            model_name="quizlabels",
            name="quiz",
        ),
        migrations.DeleteModel(
            name="Label",
        ),
        migrations.DeleteModel(
            name="QuizLabels",
        ),
    ]
