# Generated by Django 5.1.4 on 2025-04-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_remove_quiz_labels_remove_quizlabels_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="colour",
            field=models.CharField(default="#000000", max_length=7),
        ),
    ]
