# Generated by Django 5.1.4 on 2025-04-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_quiz_colour"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="colour",
        ),
    ]
