# Generated by Django 5.1.4 on 2025-04-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_remove_quiz_colour"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="thumbnail_url",
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
