# Generated by Django 5.1.4 on 2025-04-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_quiz_thumbnail_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="file_name",
            field=models.CharField(default="no_file"),
        ),
    ]
