# Generated by Django 5.1.4 on 2025-04-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_alter_quiz_file_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="file_name",
            field=models.CharField(blank=True),
        ),
    ]
