# Generated by Django 5.1.4 on 2025-04-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_attempt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attempt",
            name="correct",
        ),
        migrations.RemoveField(
            model_name="attempt",
            name="wrong",
        ),
    ]
