# Generated by Django 5.1.4 on 2025-05-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_remove_attempt_correct_remove_attempt_wrong"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="embed_url",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="thumbnail_url",
            field=models.CharField(blank=True, null=True),
        ),
    ]
