# Generated by Django 5.1.4 on 2025-05-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_alter_quiz_embed_url_alter_quiz_thumbnail_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
