# Generated by Django 5.1.4 on 2025-05-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_alter_quiz_title"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="quiz",
            name="unique_quiz_title",
        ),
    ]
